-- /main/end_game.gui_script
function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		local node = gui.get_node("restart_button")
		if gui.pick_node(node, action.x, action.y) then
			-- Освобождаем СВОЙ фокус
			msg.post(".", "release_input_focus")
			-- И отправляем сообщение в игровую сцену
			msg.post("game:/game#game_script", "start_restart_sequence")
		end
	end
	return true
end
